services:
  amazoncorretto21-ubuntu24:
    image: ${REPO_NAME:-public.container.amazoncorretto-ubuntu}:amazoncorretto21-ubuntu24-${VERSION_TAG:-snapshot}
    build:
      context: .
      dockerfile: Dockerfile
      #dockerfile: dev.Dockerfile
    command: bash /test/non_root_user_test.sh
    environment:
      ROOT_USER_SCRIPT: /test/root_user_test.sh
    volumes:
      - ./test:/test
